mkdir build
g++ -o build/acmp src/acmp.cpp
g++ -o build/caseicmp src/caseicmp.cpp
g++ -o build/casencmp src/casencmp.cpp
g++ -o build/casewcmp src/casewcmp.cpp
g++ -o build/dcmp src/dcmp.cpp
g++ -o build/fcmp src/fcmp.cpp
g++ -o build/hcmp src/hcmp.cpp
g++ -o build/icmp src/icmp.cpp
g++ -o build/lcmp src/lcmp.cpp
g++ -o build/ncmp src/ncmp.cpp
g++ -o build/pointscmp src/pointscmp.cpp
g++ -o build/rcmp src/rcmp.cpp
g++ -o build/rcmp4 src/rcmp4.cpp
g++ -o build/rcmp6 src/rcmp6.cpp
g++ -o build/rcmp9 src/rcmp9.cpp
g++ -o build/rncmp src/rncmp.cpp
g++ -o build/uncmp src/uncmp.cpp
g++ -o build/wcmp src/wcmp.cpp
g++ -o build/yesno src/yesno.cpp
