c:
  compile:
    - /usr/bin/gcc -O2 -std=c99 -o {exe_file} {code_file} -DONLINE_JUDGE -lm -fmax-errors=3
  code_file: foo.c
  exe_ext: bin
  execute: ./{exe_file}
cpp:
  compile:
    - /usr/bin/g++ -O2 -std=c++11 -o {exe_file} {code_file} -DONLINE_JUDGE -lm -fmax-errors=3
  code_file: foo.cc
  exe_ext: bin11
  execute: ./{exe_file}
cc14:
  compile:
    - /usr/bin/g++ -O2 -std=c++14 -o {exe_file} {code_file} -DONLINE_JUDGE -lm -fmax-errors=3
  code_file: foo.cc
  exe_ext: bin14
  execute: ./{exe_file}
cc17:
  compile:
    - /usr/bin/g++ -O2 -std=c++17 -o {exe_file} {code_file} -DONLINE_JUDGE -lm -fmax-errors=3
  code_file: foo.cc
  exe_ext: bin17
  execute: ./{exe_file}
pas:
  compile:
    - /usr/bin/fpc -O2 -o{exe_file} {code_file}
  code_file: foo.pas
  exe_ext: binpas
  execute: ./{exe_file}
java:
  compile:
    - /usr/bin/javac -encoding utf8 -d . {code_file}
    - /usr/bin/jar cvf {exe_file} *.class
  code_file: Main.java
  exe_ext: jar
  execute: /usr/bin/java -cp {exe_file} Main
py2:
  compile:
    - /bin/cp {code_file} {exe_file}
  code_file: foo.py
  exe_ext: py
  execute: /usr/bin/python2 {exe_file}
python:
  compile:
    - /bin/cp {code_file} {exe_file}
  code_file: foo.py
  exe_ext: py3
  execute: /usr/bin/python3 {exe_file}
pypy:
  compile:
    - /bin/cp {code_file} {exe_file}
  code_file: foo.py
  exe_ext: pypy
  execute: /usr/bin/pypy {exe_file}
pypy3:
  compile:
    - /bin/cp {code_file} {exe_file}
  code_file: foo.py
  exe_ext: pypy3
  execute: /usr/bin/pypy3 {exe_file}
text:
  compile:
    - /bin/cp {code_file} {exe_file}
  code_file: foo.txt
  exe_ext: txt
  execute: /bin/cat {exe_file}
